# Custom/Local Paths for PreTeXt Website build script

# ***********************************************************************
#                       DO NOT EDIT THIS FILE
#
#   IT WILL BE OVERWRITTEN WITH UPDATES AND YOUR CHANGES WILL BE LOST
#
# Instead, 
#   1. make a copy of this file, in the same directory, named  paths.sh
#   2. edit it, based on local locations, items below are just suggestions
#   3. remove this warning so you don't get confused
#   4. periodically check for changes in paths.template.sh (see History)
# ***********************************************************************

# History
#
# 2025-11-12 Fresh start
# 2025-11-12 REPOS, STAGED, LOCALPTX
# 2025-11-17 SCRATCH
# 2025-12-24 Made STAGED and SCRATCH automatic


# Various repositories are involved in building material
# for the website.  You should have a home for them.  The
# build script will automatically due a pull on each one
# to refresh it before using it in an updated builld
declare REPOS=${HOME}/path/to/repos

# The build script may be run (optionally) with local,
# non-public, versions of some of the inputs.  Declare
# their alternate locations here.
declare LOCALPTX=${HOME}/path/to/pretext
